### ISSUE TITLE
Wanted: HOI4 Savegames

### ISSUE THREAD

**Issue by crschnick** [crschnick/pdx_unlimiter#10]
Here you can share your HOI4 savegames. Either upload it here in a zip or share a link to a cloud storage. You can also share these links with me on reddit.

**Comment by Idhrendur** [comment]
Here's a USA game I have. Ironman, no mods.
[USA.zip](https://github.com/crschnick/pdx_unlimiter/files/5580034/USA.zip)

**Comment by Acee5** [comment]
[saves.zip](https://github.com/crschnick/pdx_unlimiter/files/5582269/saves.zip)

**Comment by crschnick** [comment]
Closed, someone sent me 2GB of saves, that should be enough
