### ISSUE TITLE
CK2 ironman save game export doesnt work because file name is incorrect

### ISSUE THREAD

**Issue by ghostcaesar** [crschnick/pdx_unlimiter#102]
CK2 exports changes file name from original save. 

CK2 doesnt allow loading of ironman saves when save file name is changed.

For CK2, exported save should match imported save file name. (Alternatively I believe the file name is also stored in the meta file when editing save file)

**Comment by crschnick** [comment]
Hmm I didn't know about that. I think this should be fixable though. As a workaround, you can just create a save in-game with the country name such that the name stays the same when being exported.

**Comment by crschnick** [comment]
Do you know whether the same applies for Victoria2?

**Comment by crschnick** [comment]
This should be fixed now in the latest release
