### ISSUE TITLE
ctrl+shift+r in eu4 opens several instances of eu4

### ISSUE THREAD

**Issue by pgsandstrom** [crschnick/pdx_unlimiter#107]
I have Windows 11, lolz. Also my computer is mega ultra super quick, maybe that has something to do with it?

**Comment by crschnick** [comment]
Ok so I tried to reproduce this issue but couldn't. In fact, it seems like on my end there's something not working correctly as it sometimes does not launch an instance at all. So I will investigate that

**Comment by pgsandstrom** [comment]
Yeah, you know, today it changed into not launching at all, like you described. I have no idea what brought about this change.

**Comment by crschnick** [comment]
This should be fixed now in the latest release

**Comment by fedeoeae** [comment]
That could be possible, but it's waay too consistent for that, imo. It ALWAYS opens up 3 times, no matter how hard or soft I press the key.

Pressing multiple times seems to open it even more often. It semms to struggle to kill the "new" ones. Maybe adding a timer (so it doesn't run if it ran in the last 2 seconds) would fix it, though no idea how hard that is to do.

**Comment by crschnick** [comment]
Alright I can try to implement a timer to avoid multiple starts. But I'm still unsure what can cause that behavior as it does not happen for me.

What does the log file say when it opens for you multiple times? Does it also print multiple times that the key was pressed? Essentially is this run multiple times: https://github.com/crschnick/pdx_unlimiter/blob/c23498c09db04b09007752cc4d09ce60bf89532b/pdxu-app/src/main/java/com/crschnick/pdxu/app/installation/GameKeyListener.java#L16

**Comment by fedeoeae** [comment]
Sorry, no Idea. Also, it seems to have stopped after a PC restart.

**Comment by crschnick** [comment]
This is now fixed properly
