### ISSUE TITLE
how to change default file associations (or prevent pdxu from making itself default in first place)?

### ISSUE THREAD

**Issue by Spacewolf4** [crschnick/pdx_unlimiter#110]
OK, so. Pdx-U makes itself the default file association for several file extensions used by paradox games.

For extensions like .hoi4, .ck3, .eu4, this makes sense, no problem.

But .sav? .txt? Those are used by way more than just Paradox games. How do I switch it back in Win 11, and is there a way to stop the windows installer from making it the default in the first place?

**Comment by crschnick** [comment]
The installer registers all default file types for paradox games, but not .txt. What it also does is advertise the mime-types, so maybe your OS lists pdxu as an possible txt editor as the save game mime type is `text/plain` but it should not use it as a default editor for that. The .sav extension registration might have been an oversight as I did not know that many other games also use that one.

Right now there is no way to tell the installer to not register the file extensions. But it should be possible to just set your preferred program to be the default one for a certain file type in windows. You can also of course uninstall pdxu and use the portable version instead.

The main problem is that I can't simply change the existing installer as that would reset the Microsoft SmartScreen trust level and show warnings for everyone, so I try to avoid that.

**Comment by crschnick** [comment]
I think the reason why Windows is confused about the associations is that pdxu is probably the only program that correctly reports mime-types to the OS. In most cases this isn't a big issue, but e.g. web browsers care about them and then prefer pdxu.

**Comment by crschnick** [comment]
Yes it is a mess because some save games are zips and some of them are text, so it advertises support for both types. If you don't want to meddle with the registry, I would just use the portable version to disable these claimed extensions.

**Comment by crschnick** [comment]
I guess we can close this issue then even though the solution is not very satisfactory as I have no influence over mime type handling
