### ISSUE TITLE
Issue fater 1.37.5 in eu4

### ISSUE THREAD

**Issue by Vwsper** [crschnick/pdx_unlimiter#130]
I had all dlc of eu4, but after update 1.37.5 when some dlc was added to base game my saves in pdx unlimter crashed cause:

The following DLCs are missing:
- Art of War
- Common Sense
- Rights of Man

**Comment by gebau00a** [comment]
These DLCs are added in the base game.
This was settled with 2.13.13.
Have you tried this version already?

**Comment by KitiHey** [comment]
I have the same issue here, i have the last version of pdx unlimiter but still have the problem

**Comment by crschnick** [comment]
Are you on macos?

**Comment by crschnick** [comment]
And your pdxu version is showing as 2.13.13?

**Comment by KitiHey** [comment]
> And your pdxu version is showing as 2.13.13?

yep

**Comment by crschnick** [comment]
Can you go to Steam and validate your game files. and restart pdxu after that?

**Comment by Vwsper** [comment]
> These DLCs are added in the base game. This was settled with 2.13.13. Have you tried this version already?

I have latest version of pdx unlimiter

**Comment by Vwsper** [comment]
Windows, and I don't know why, but after a while the saves started working

**Comment by KitiHey** [comment]
> Can you go to Steam and validate your game files. and restart pdxu after that?

I have the dlcs pirated so that could be the problem, what it seems is that pdx unlimiter just deactivates some of my music packs and pops that error, when i open my launcher and use it after using pdx unlimiter it pops the error except if i do not turn the music packs that pdx has turned me off.

**Comment by crschnick** [comment]
... that might explain your issue. Pdxu is made using the steam version in mind, so there seem to be some differences in your case. If your game files would match the steam version, there shouldn't be an issue. So can probably report this issue to where you pirated it from as I can't fix that.

**Comment by KitiHey** [comment]
> ... that might explain your issue. Pdxu is made using the steam version in mind, so there seem to be some differences in your case. If your game files would match the steam version, there shouldn't be an issue. So can probably report this issue to where you pirated it from as I can't fix that.

Yep, but i think the only problem for me is with music packs because when i turn them on again (disables by pdx unlimiter) the problem goes away. My eu4 is purchased from steam but only the dlcs are pirated. Ig the solution is to just disable the music packs for my next games and that's all, idk for the main guy tbf

**Comment by crschnick** [comment]
Have you tried verifying your steam game files is your main game is on Steam?

**Comment by Vwsper** [comment]
> Have you tried verifying your steam game files is your main game is on Steam?

all files have successfully passed the check, and I don't have any pirated DLCs, now everything somehow worked on its own despite the notification about the possibility of breaking saves - they work, but it seems to me the problem may return

**Comment by KitiHey** [comment]
The problem right now with pirated dlcs are the 3 dlcs which are now in the base game, which unlimiter doesnt enable. But because i have them pirated those werent removed and those things. So problem solved for me

**Comment by crschnick** [comment]
Ok so for the both of you, you should find these missing DLCs in your Steam base game now at `C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV\builtin_dlc` (or wherever you have your steam installation). Are the DLCs there for you? Pdxu should load them from there now

**Comment by KitiHey** [comment]
> Ok so for the both of you, you should find these missing DLCs in your Steam base game now at `C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV\builtin_dlc` (or wherever you have your steam installation). Are the DLCs there for you? Pdxu should load them from there now

Yep they are there, but pdxu doesnt load them atleast in my already made save game

**Comment by crschnick** [comment]
Ok, can you share the .dlc file contents? That is the only way that pdxu doesn't load it, if the .dlc file does not look as expected.
![image](https://github.com/user-attachments/assets/8490b44c-ecb2-4a1c-9333-b035749812a9)

**Comment by KitiHey** [comment]
but i see that the problem for me are just those 5 music packs that pdxu doesnt activate me, prob because they are at base game already and pdxu doesnt activate them

**Comment by Vwsper** [comment]
> Ok so for the both of you, you should find these missing DLCs in your Steam base game now at `C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV\builtin_dlc` (or wherever you have your steam installation). Are the DLCs there for you? Pdxu should load them from there now

Yes, they are in the folder

**Comment by Vwsper** [comment]
![Снимок экрана 2024-10-27 213843](https://github.com/user-attachments/assets/44397e60-45c1-4509-8a11-9f83c9d071af)
![Снимок экрана 2024-10-27 213939](https://github.com/user-attachments/assets/d4ed8065-3c21-46cd-ab78-73c21b7fc70b)
![Снимок экрана 2024-10-27 213947](https://github.com/user-attachments/assets/04e39e0d-cc8d-41f3-8fa0-a798f6f27c11)

**Comment by crschnick** [comment]
How does your .dlc look like? Mine looks like this:
```
name = "Art of War"
archive = "builtin_dlc/dlc027_art_of_war/dlc027.zip"
pops_id = "eu4_dlc027_art_of_war"
affects_checksum = no
affects_compatability = yes
checksum = "5ef000d74abd9c779a9b5066f7e7bd35"
category = "expansion"
```

**Comment by Vwsper** [comment]
![Снимок экрана 2024-10-27 214811](https://github.com/user-attachments/assets/fa8630ae-8128-423f-b7e6-91ffc0bc2a5c)

**Comment by Vwsper** [comment]
exactly the same

**Comment by Vwsper** [comment]
![Снимок экрана 2024-10-27 214953](https://github.com/user-attachments/assets/1bd63f4a-6e4e-4da8-8483-f687759ed492)

**Comment by Vwsper** [comment]
![Снимок экрана 2024-10-27 215148](https://github.com/user-attachments/assets/b52c1caf-3f77-4c8a-b8a4-d4257d4951c3)

**Comment by Vwsper** [comment]
But now it works, i dont know why

**Comment by KitiHey** [comment]
> ![Снимок экрана 2024-10-27 215148](https://private-user-images.githubusercontent.com/49849190/380502186-b52c1caf-3f77-4c8a-b8a4-d4257d4951c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzc0MjgsIm5iZiI6MTczMDAzNzEyOCwicGF0aCI6Ii80OTg0OTE5MC8zODA1MDIxODYtYjUyYzFjYWYtM2Y3Ny00YzhhLWI4YTQtZDQyNTdkNDk1MWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEzNTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjkyY2NmM2U5ZDUzOGY1OTM3N2U0MWU2YmY3N2Y0MDc2NDJjMzJkZGM5YmJkNDFhZDY5OWUwNDc4YmNiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QvT9u9Bbopl-Mx-qONvoPyLdYrmdkhKTaDVjk2AWh9A)

For me just appears ingame, for whatever reason i mentioned

**Comment by crschnick** [comment]
Can you try this: https://we.tl/t-lJxdAhkrAV

**Comment by Vwsper** [comment]
> Can you try this build: https://we.tl/t-lJxdAhkrAV

I can't, I'm from Russia and this site won't let me access it even with a VPN

**Comment by crschnick** [comment]
What about this: https://easyupload.io/c37yez

**Comment by Vwsper** [comment]
java.nio.file.NoSuchFileException: C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV\dlc\dlc001_100_years_war_unit_pack\dlc001_100_years_war_unit_pack.dlc
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3268)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.parser.TextFormatParser.parse(TextFormatParser.java:115)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameDlc.fromDirectory(GameDlc.java:31)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallType.lambda$loadDlcsFromDirectory$0(GameInstallType.java:770)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallType.loadDlcsFromDirectory(GameInstallType.java:768)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallType$1.loadDlcs(GameInstallType.java:47)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallation.loadDlcs(GameInstallation.java:108)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallation.initOptional(GameInstallation.java:102)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.installation.GameInstallation.init(GameInstallation.java:81)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.ComponentManager.init(ComponentManager.java:133)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Vwsper** [comment]
![image](https://github.com/user-attachments/assets/ed3dc960-7308-4012-bd56-f7b07e0af1a8)

**Comment by Vwsper** [comment]
But after I click OK, the program works and all dlc are visible
![image](https://github.com/user-attachments/assets/cac989ba-90e2-40c6-b2b0-f21dba22724b)

**Comment by Vwsper** [comment]
Thank you a lot, I think there will be no problems with this build, I can't imagine how I used to play Paradox games without your program

**Comment by crschnick** [comment]
Does this work as well without the error: https://easyupload.io/r4y2w6

**Comment by Vwsper** [comment]
> Does this work as well without the error: https://easyupload.io/r4y2w6

Its works without any issues, thank you

**Comment by crschnick** [comment]
This should be fixed now in the latest release
