### ISSUE TITLE
Campaign.json and its backup corrupted after pc crashing

### ISSUE THREAD

**Issue by ensvrd** [crschnick/pdx_unlimiter#134]
My campaigns.json got corrupted after my pc crashed. Both backup and original file had to be deleted in order to get it to work again. Is there any way to get back my saves? Individual save files are not deleted.

**Comment by crschnick** [comment]
You can try moving the saves into a different directory, and then drag and drop that directory into pdxu. That should reimport them again

**Comment by ensvrd** [comment]
Oh thank you. I found out I had 175 gbs of save files so it took a while and I had to wipe them except my last save. Thanks a lot
