### ISSUE TITLE
Pressing CTRL + C in any window while the program is open kills Stellaris instantly and opens up a menu talking about mods

### ISSUE THREAD

**Issue by HimitsuYami** [crschnick/pdx_unlimiter#136]
Pretty much what the title says, if I press CTRL + C in any window (such as to copy text from notepad or VSC) while this program is open, Stellaris IMMEDIATELY closes, no save, no delay, no confirmation. This is _very_ frustrating when I want to copy an event ID or something to paste into the game console only to watch as the game closes and a menu mentioning the save game not storing mods pops up

**Comment by crschnick** [comment]
The shortcut for that is CTRL+SHIFT+C, so it shouldn't trigger on only CTRL+C.

**Comment by HimitsuYami** [comment]
I'm not sure what to tell you, but it triggers on CTRL+C for me. But it also doesn't seem like something that should trigger when I'm copying text in notepad or VSC for example

**Comment by crschnick** [comment]
What OS is this? It doesn't do that on Windows 10 for me.

**Comment by HimitsuYami** [comment]
Windows 10

**Comment by HimitsuYami** [comment]
I notice it happens if I use control and shift to highlight text, let off of shift, and then press c

**Comment by crschnick** [comment]
I tried that. It should only trigger when all 3 buttons are down and does for me. Is your shift stuck?

**Comment by HimitsuYami** [comment]
It might be getting stuck sometimes, that would explain it a bit. Is there a way to disable this shortcut? I never intentionally use it as I like to manage the shutdown myself as long as the game isn't stuck (in which case I just use task manager anyway). when this happens, it also disables Irony's resume function, so it takes even longer to get back into the game for me.

**Comment by crschnick** [comment]
You can edit the .cfg file in `C:\Users\<User>\AppData\Local\Programs\Pdx-Unlimiter\app\app` and add `-DenableJNativeHook=false` as an argument

**Comment by crschnick** [comment]
That would disable all shortcuts

**Comment by HimitsuYami** [comment]
I can do that, thank you so much for the help!

**Comment by crschnick** [comment]
Ehm, that might work I just realized.

**Comment by HimitsuYami** [comment]
Might?

**Comment by crschnick** [comment]
You have to create a file in <Documents Dir>/Pdx-Unlimiter called `pdxu.properties` with `enableJNativeHook=false` instead

**Comment by HimitsuYami** [comment]
in Documents or one of the subfolders like settings?

**Comment by crschnick** [comment]
`<Documents>/Pdx-Unlimiter/settings`

**Comment by HimitsuYami** [comment]
Done, I have `pdxu.properties` in `%homepath%\Documents\Pdx-Unlimiter\settings` with just the one line reading `DenableJNativeHook=false` but that didn't stop it (after restarting pdxu)

**Comment by crschnick** [comment]
without the D in this case

**Comment by HimitsuYami** [comment]
So, `enableJNativeHook=false`? Just to confirm

**Comment by crschnick** [comment]
yes

**Comment by HimitsuYami** [comment]
That worked! Thanks a bunch!
