### ISSUE TITLE
NoSuchFileException with Blank EU4 Install

### ISSUE THREAD

**Issue by nickbabcock** [crschnick/pdx_unlimiter#16]
![image](https://user-images.githubusercontent.com/2106129/101769510-b1667580-3aac-11eb-866a-788f7a192654.png)

I can workaround this by creating the directory

**Comment by crschnick** [comment]
Do you have EU4 installed and is the EU4 savegame directory at that location? I usually assume that the directory exists when an EU4 installation is detected
