### ISSUE TITLE
Having a lot of save games causes the import save game window to vertically exceed the screen size and be unable to be resized

### ISSUE THREAD

**Issue by Thradius** [crschnick/pdx_unlimiter#22]

**Comment by crschnick** [comment]
I will fix that shortly. Meanwhile, you can bypass the importer dialog by just dragging and dropping savegame files into the Pdx-Unlimiter directly.

**Comment by crschnick** [comment]
Should be fixed in the new release available now

**Comment by crschnick** [comment]
Fixed
