### ISSUE TITLE
Ctrl-Shift-I while the game is running did not import the latest saved game while the game was running

### ISSUE THREAD

**Issue by Thradius** [crschnick/pdx_unlimiter#23]
I imported a single save from a current patch game as france and decided to try out the feature. I saved manually in the game and then hit ctrl-shift-I and then went to look at the tool the see what happened and I noticed that nothing had changed about my france game... but a new game had appeared on the list on the left... an ancient save from an old incompatible patch as Desmond. I don't even know where that save resides on my hard drive, but I recall playing games as them several years ago.

**Comment by crschnick** [comment]
Whoops, seems like the order was reversed and it always imports the oldest savegame.
