### ISSUE TITLE
Alt-F4 or Ctrl-Shift-K out of game but selecting latest save in tool does not update the bottom bar to green and show launch button

### ISSUE THREAD

**Issue by Thradius** [crschnick/pdx_unlimiter#27]
It stays white, and only shows "Import" as an option in the lower right. Selecting a different save in the left panel, and then selecting a save in the right panel resets the bottom bar to green, and you can then reselect the most recent save in the left and then right in order to hit launch again.

**Comment by crschnick** [comment]
Yeah I just reproduced this issue, will fix it in the next update

**Comment by crschnick** [comment]
ixed
