### ISSUE TITLE
Queen is displayed as ruler even though the ruler is the King

### ISSUE THREAD

**Issue by Thradius** [crschnick/pdx_unlimiter#33]
Maybe because I had a female ruler in the past?

**Comment by crschnick** [comment]
Can you share the savegame so I can easily reproduce this?

**Comment by Thradius** [comment]
[France (3 November, 1586).txt](https://github.com/crschnick/pdx_unlimiter/files/5819085/France.3.November.1586.txt)
Change the .txt to .eu4 to use :D

**Comment by crschnick** [comment]
Should be fixed in the next release
