### ISSUE TITLE
Looking for someone who is interested in porting this to Mac

### ISSUE THREAD

**Issue by crschnick** [crschnick/pdx_unlimiter#54]
Note that this would be a little bit more work than just running `gradle build`, especially generating the installers with jlink and jpackage, adapting the file paths, and detecting and fixing platform specific issues/bugs. The Linux port had countless problems with GTK and crashes, so I don't expect everything to work smoothly on Mac.

But if you are still interested, I can assist you with basically everything listed here.

**Comment by gebau00a** [comment]
I can take a look, I have a M1 Mac to try to help porting

**Comment by crschnick** [comment]
Oh wow, that sounds nice. How familiar are you with java development? You don't really have to be that familiar as I can do most of the stuff, would be just good to know.

**Comment by gebau00a** [comment]
15 years ago I was quite good in Java, but lost track on new developments.
Any guide what is needed, can be either English or German

**Comment by crschnick** [comment]
All right, this sounds like a good basis. I think the best way of handling the communication would be on the discord server (if you have a discord account)

Ideally this port will go relatively smoothly as I already spent some time proactively fixing things for mac, even though I couldn't test it.

**Comment by crschnick** [comment]
Here is the result: https://github.com/crschnick/pdx_unlimiter/releases/tag/2.10.2-pre

**Comment by crschnick** [comment]
Closing this as completed
