### ISSUE TITLE
Looking for people interested in translating the interface messages into their languages

### ISSUE THREAD

**Issue by crschnick** [crschnick/pdx_unlimiter#55]
You can find existing translations [here](https://github.com/crschnick/pdx_unlimiter/blob/master/app/lang/settings_l_english.yml).

Note that this is only a small part of all translatable messages, the rest is just not outsourced into separate language files yet.
But I can easily do that, once someone wants to translate the other strings as well.

**Comment by KostiaChardonnet** [comment]
I can translate it in french.

**Comment by crschnick** [comment]
Ok that's great! I can write up a quick general guide soon and also add support to change your language in the Pdx-Unlimiter, so that you can see how your translation looks like when it is applied.

**Comment by crschnick** [comment]
Ok, I pushed the required changes into master. You can now add translations (for certain parts) by creating and filling out the appropriate files in `app/lang/`. You can also see your translations in action by changing to your language in the settings menu.

I will try to move more translatable strings from the codebase into language files next.

**Comment by crschnick** [comment]
@KostiaChardonnet See #58

**Comment by crschnick** [comment]
Close for #58

**Comment by Ikumyon** [comment]
I've translated the file into Japanese.

**Comment by crschnick** [comment]
> I've translated the file into Japanese.

That is great to hear! You can either create a pull request here on GitHub or upload the translation files somewhere for me to add them.

**Comment by crschnick** [comment]
Alright, I added your translation to the repository in 45ad62b . The translations will then be included in the next release, which I will hopefully be able to release soon.

**Comment by Ikumyon** [comment]
That's why it didn't switch well when I switched languages, thank you for fixing that.

**Comment by crschnick** [comment]
@Ikumyon Your translations are now live with the latest release

**Comment by EnzoMaitan** [comment]
Hello, I would like to know if translations are still wanted, since this thread has not been active for a while. I could start working on a Brazilian Portuguese translation

**Comment by crschnick** [comment]
Yes, the instructions in https://github.com/crschnick/pdx_unlimiter/issues/58 are still up to date
