### ISSUE TITLE
App not launching?

### ISSUE THREAD

**Issue by Dreadcliff** [crschnick/pdx_unlimiter#68]
On attempting to launch the app, it opens a blank window, and stops responding. It is important to note I am on windows 7

Most recent log attached
[pdxu_2021-06-23_04-27-13.log](https://github.com/crschnick/pdx_unlimiter/files/6700688/pdxu_2021-06-23_04-27-13.log)

**Comment by crschnick** [comment]
Can you show me a screenshot of the blank window so that I know exactly what you mean?

**Comment by Dreadcliff** [comment]
Realized it would probably be prudent to upload other logs, along with a screenshot of the window.
[pdxu_2021-06-23_04-34-37.log](https://github.com/crschnick/pdx_unlimiter/files/6700705/pdxu_2021-06-23_04-34-37.log)
[pdxu_2021-06-23_04-26-13.log](https://github.com/crschnick/pdx_unlimiter/files/6700706/pdxu_2021-06-23_04-26-13.log)
[pdxu_2021-06-23_04-04-53.log](https://github.com/crschnick/pdx_unlimiter/files/6700707/pdxu_2021-06-23_04-04-53.log)
[pdxu_2021-06-23_02-33-50.log](https://github.com/crschnick/pdx_unlimiter/files/6700708/pdxu_2021-06-23_02-33-50.log)
[pdxu_2021-06-23_02-32-19.log](https://github.com/crschnick/pdx_unlimiter/files/6700709/pdxu_2021-06-23_02-32-19.log)
[pdxu_2021-06-23_02-19-27.log](https://github.com/crschnick/pdx_unlimiter/files/6700710/pdxu_2021-06-23_02-19-27.log)
[pdxu_2021-06-23_02-16-27.log](https://github.com/crschnick/pdx_unlimiter/files/6700711/pdxu_2021-06-23_02-16-27.log)
[pdxu_2021-06-23_02-17-32.log](https://github.com/crschnick/pdx_unlimiter/files/6700712/pdxu_2021-06-23_02-17-32.log)
![Capture](https://user-images.githubusercontent.com/59663086/123074048-98843880-d3dc-11eb-85a8-3a7e012e388c.PNG)

**Comment by Dreadcliff** [comment]
All logs are the same, with no error listed.

**Comment by crschnick** [comment]
Can you share your `settings.json` and `state,json` located at `<Documents>\Pdx-Unlimiter\settings`? Also, did it ever work properly or is this the first time your using it?

**Comment by Dreadcliff** [comment]
This is my first time using it, and the neither of those files exist in the settings folder.

**Comment by Dreadcliff** [comment]
I've already tried the repair function on the installer

**Comment by Dreadcliff** [comment]
Screenshot of the contents of my settings folder.
[settingsFolder](https://user-images.githubusercontent.com/59663086/123076348-ab980800-d3de-11eb-9652-7cda00057e1d.PNG)

**Comment by crschnick** [comment]
I can quickly create a debug build for you to test which has a lot more logging output to narrow down whats happening

**Comment by Dreadcliff** [comment]
let's try that

**Comment by Dreadcliff** [comment]
I'm going to have to go for today, and won't be able to post the run the debug build or post the logs until tomorrow, so don't rush.

**Comment by crschnick** [comment]
You can download the debug build [here](https://github.com/crschnick/pdx_unlimiter/releases/tag/2.7.3-pre).
Just extract it anywhere you want and double click the `pdxu-debug.bat` file

**Comment by Dreadcliff** [comment]
Here's the new log file
[pdxu_2021-06-24_03-22-56.log](https://github.com/crschnick/pdx_unlimiter/files/6707597/pdxu_2021-06-24_03-22-56.log)
After checking for an EU4 installation, it looks like it just stops.

**Comment by crschnick** [comment]
Ok, that narrows it down. I suspect it has something to do with the Windows Store game installation check. I updated the build [here](https://github.com/crschnick/pdx_unlimiter/releases/tag/2.7.3-pre), can you try this one?

**Comment by Dreadcliff** [comment]
That fixed it, thanks for the help.

**Comment by crschnick** [comment]
Thas's good news! I will push the update soon so that you don't have to use the dev build with the console.

**Comment by crschnick** [comment]
The update is pushed, you should be able to start the Pdx-Unlimiter now with the normal installation.
