### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by crschnick** [crschnick/pdx_unlimiter#8]

**Comment by bherw** [comment]
What needs to be done for this? Just EU4 installation autodetection or is there more cross-platform work needed?

**Comment by crschnick** [comment]
It should be working on linux, the main focus is creating a downloadable release package and testing it on some systems.

I recently added a debian package build task [here](https://github.com/crschnick/pdxu_launcher/blob/master/build.gradle)

**Comment by bherw** [comment]
It'd be nice to get the package adhering to standard linux directories if possible. libs in /usr/lib, resources in /usr/share. I'll see about testing it later; I have a Gentoo system, but I can probably write an ebuild to pull the relevant files from the debian package.

**Comment by bherw** [comment]
Is JDK15 a hard requirement for anything or will JDK8 work as well? Gentoo defaults to icedtea, which is based on JDK8.

**Comment by crschnick** [comment]
JDK15 is a requirement, since this project is using many new features including [jlink](https://docs.oracle.com/en/java/javase/11/tools/jlink.html). An end user doesn't have to install java anymore, it is only needed for development

**Comment by crschnick** [comment]
Added
