### ISSUE TITLE
How do you find the DNA of characters using this mod?

### ISSUE THREAD

**Issue by AngerySnek** [crschnick/pdx_unlimiter#80]
Thanks for any answers, I appreci8

**Comment by crschnick** [comment]
When you open a savegame in the editor, you have to navigate to the character you want to inspect.
For example, you can quickly jump to the player character by clicking on `Jump To` -> `Player character`.

![image](https://user-images.githubusercontent.com/72509152/168292158-3a03a76a-93ea-4dbb-bb82-83596cfe84ad.png)

**Comment by crschnick** [comment]
Closing this if there are no further questions
