### ISSUE TITLE
Could you add a way to revive dead characters with this mod?

### ISSUE THREAD

**Issue by AngerySnek** [crschnick/pdx_unlimiter#82]
Thank you

**Comment by crschnick** [comment]
Now in theory everything is possible with savegame editing (although it takes a lot of effort).

The problem with reviving is that all data like titles etc. is removed from a character once it dies.
To revive a character, I would look it up in `dead_unprunable/<char id>`, move it to `living/<char id>` and remove the field `dead_data` from it.

**Comment by crschnick** [comment]
Closing this for now

**Comment by AngerySnek** [comment]
> Now in theory everything is possible with savegame editing (although it takes a lot of effort).
> 
> The problem with reviving is that all data like titles etc. is removed from a character once it dies. To revive a character, I would look it up in `dead_unprunable/<char id>`, move it to `living/<char id>` and remove the field `dead_data` from it.

Hey, thank you. Sorry for late reply
How do I copy a dead character file to the living character files in pdx unlimiter?

**Comment by crschnick** [comment]
Also sorry for my late reply, I'm also quite busy right now.

About the character modifications in general, I would advise you to stay away from it, especially if you're not experienced with it.
The CK3 save game structure is horrible for editing characters and even small changes can be very complex.

About the copy, paste, and deletion of files in the editor: The editor currently does not support these operations, it is a very primitive tool to edit game files and save games. You would have to perform these operations outside of the editor.
In case you're asking about how to copy paste or delete save games: https://github.com/crschnick/pdx_unlimiter/wiki/User-Guide#savegame-actions
