### ISSUE TITLE
Steam not detected

### ISSUE THREAD

**Issue by Douchebert** [crschnick/pdx_unlimiter#84]
![image](https://user-images.githubusercontent.com/51342603/180756205-1577c51a-7d9e-4ae2-ac69-79a94991acf0.png)
Steam is very much started, and I can start using the "Start in launcher" or "-> Launch", but not "continue game", if I try to continue then this alert shows.

**Comment by crschnick** [comment]
Fixed in https://github.com/crschnick/pdx_unlimiter/releases/tag/2.10.1-pre

**Comment by crschnick** [comment]
Fixed in the latest release
