### ISSUE TITLE
Issue with Lions of the North Update

### ISSUE THREAD

**Issue by real-csabb** [crschnick/pdx_unlimiter#86]
Hi there, crschnick,

I noticed that PDX_Unlimiter is broken in the Lions of the North update. Whenever you Ctrl-C and get back in-game, achievements are disabled because you're either offline and/or the save is not yours. I hope you can fix this soon!

**Comment by crschnick** [comment]
Can you try using the latest Pdx-Unlimiter version and launching the game normally through the launcher one time before?
I found that updating to the next game version and using the Pdx-Unlimiter without running the game launcher once breaks some things

**Comment by crschnick** [comment]
Also, save games from previous game versions do not seem to work properly

**Comment by crschnick** [comment]
Are you using 2.10.2?

**Comment by real-csabb** [comment]
I'm using version 2.10.0 of PDX_Unlimiter. Is that the problem?

**Comment by crschnick** [comment]
yes you need to update in order to make it work properly for the newest version of EU4

**Comment by real-csabb** [comment]
Oh, that's my bad, sorry. How do I update?

**Comment by crschnick** [comment]
That depends on the kind of distribution you use. If you use the portable zip, you need to download the new version manually

**Comment by real-csabb** [comment]
Is there any way to check which distro I'm on? I don't remember.

**Comment by crschnick** [comment]
If it shows up in your control panel under programs, then you use the installation distribution. In that case, it should download the update automatically the next time you start it unless you have disabled that option in the settings of the Pdx-Unlimiter. Otherwise, you used a stand alone zip version, and need to update manually

**Comment by real-csabb** [comment]
It shows up under my control panel and I have auto updated enabled in my settings.

**Comment by crschnick** [comment]
What happens if you restart it? Maybe try to start menu shortcut to launch it

**Comment by real-csabb** [comment]
Starting it from the start menu instead of the taskbar fixed it and I updated to 2.10.2. That's the correct version, right?

**Comment by crschnick** [comment]
Yes, you may have pinned the internal executable to the task bar and not the launcher executable that performs the update. If you pit the start menu or desktop shortcut to the taskbar, the updates should always work.

**Comment by real-csabb** [comment]
Gotcha. I'll fix that for the future. I just tried Ctrl-C in-game and it loaded back into my save successfully with achievements enabled. Tysm crschnick!
